[CmdletBinding()]
param(
    [string]$RepoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path,
    [switch]$Check
)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
$exportRoot = Join-Path $repoRoot "markdown_export"
$indexRoot = Join-Path $repoRoot "docs\index"
$markdownIndexPath = Join-Path $indexRoot "GDD_SOURCE_INDEX.md"
$jsonIndexPath = Join-Path $indexRoot "gdd_source_index.json"

function Get-PortablePath {
    param([Parameter(Mandatory)][string]$Path)

    return ($Path -replace "\\", "/")
}

function Get-CleanTitle {
    param([Parameter(Mandatory)][string]$FileName)

    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($FileName)
    return ($baseName -replace "\s+[0-9a-f]{32}$", "").Trim()
}

function Get-SectionInfo {
    param([Parameter(Mandatory)][string]$CleanTitle)

    if ($CleanTitle -match "^(\d+(?:\s+\d+)*)\s+(.+)$") {
        $parts = @($Matches[1] -split "\s+")
        $sortKey = (($parts | ForEach-Object { "{0:D4}" -f [int]$_ }) -join ".")
        return [pscustomobject]@{
            Path = ($parts -join ".")
            SortKey = $sortKey
            Top = [int]$parts[0]
            Depth = $parts.Count
            Title = $Matches[2].Trim()
        }
    }

    return [pscustomobject]@{
        Path = ""
        SortKey = "9999"
        Top = 999
        Depth = 0
        Title = $CleanTitle
    }
}

function ConvertTo-MarkdownTableCell {
    param([AllowNull()][string]$Value)

    if ($null -eq $Value) {
        return ""
    }

    return (($Value -replace "\|", "\|") -replace "\r?\n", " ").Trim()
}

function ConvertTo-MarkdownLinkLabel {
    param([Parameter(Mandatory)][string]$Value)

    return ((ConvertTo-MarkdownTableCell -Value $Value) -replace "\[", "\[" -replace "\]", "\]")
}

function ConvertTo-RelativeMarkdownLink {
    param([Parameter(Mandatory)][string]$FileName)

    return "../../markdown_export/$([uri]::EscapeDataString($FileName))"
}

function New-GddIndex {
    if (-not (Test-Path -LiteralPath $exportRoot)) {
        throw "Missing markdown export root: $exportRoot"
    }

    $markdownFiles = @(Get-ChildItem -LiteralPath $exportRoot -File -Filter "*.md" | Sort-Object Name)
    if ($markdownFiles.Count -eq 0) {
        throw "No Markdown files found in $exportRoot"
    }

    $records = @()
    foreach ($file in $markdownFiles) {
        $raw = Get-Content -LiteralPath $file.FullName -Raw
        $cleanTitle = Get-CleanTitle -FileName $file.Name
        $section = Get-SectionInfo -CleanTitle $cleanTitle
        $firstHeading = ""

        foreach ($line in ($raw -split "\r?\n")) {
            if ($line -match "^#\s+(.+)$") {
                $firstHeading = $Matches[1].Trim()
                break
            }
        }

        if ([string]::IsNullOrWhiteSpace($firstHeading)) {
            $firstHeading = $section.Title
        }

        $records += [pscustomobject]@{
            section = $section.Path
            sort_key = $section.SortKey
            top_section = $section.Top
            depth = $section.Depth
            title = $section.Title
            first_heading = $firstHeading
            file = (Get-PortablePath -Path ("markdown_export\" + $file.Name))
            bytes = $file.Length
            lines = (($raw -split "\r?\n") | Measure-Object).Count
            words = ([regex]::Matches($raw, "\S+")).Count
        }
    }

    $topSectionRecords = @($records | Where-Object { $_.depth -eq 1 } | Sort-Object top_section)
    $sectionSummaries = @()
    foreach ($top in ($records | Group-Object top_section | Sort-Object { [int]$_.Name })) {
        $topNumber = [int]$top.Name
        $topRecord = @($topSectionRecords | Where-Object { $_.top_section -eq $topNumber } | Select-Object -First 1)
        $label = if ($topRecord) { $topRecord.title } else { "Unsectioned" }
        $sectionSummaries += [pscustomobject]@{
            section = $topNumber
            title = $label
            files = $top.Count
            bytes = (($top.Group | Measure-Object -Property bytes -Sum).Sum)
            words = (($top.Group | Measure-Object -Property words -Sum).Sum)
        }
    }

    $md = [System.Collections.Generic.List[string]]::new()
    $md.Add("# GDD Source Index")
    $md.Add("")
    $md.Add('Generated by `scripts/build-gdd-index.ps1`. Regenerate after raw Markdown export changes.')
    $md.Add("")
    $md.Add("## Summary")
    $md.Add("")
    $md.Add("- Markdown files: $($records.Count)")
    $md.Add('- Source root: `markdown_export/`')
    $md.Add('- Structured index: `docs/index/gdd_source_index.json`')
    $md.Add("")
    $md.Add("## Top-Level Sections")
    $md.Add("")
    $md.Add("| Section | Title | Files | Words |")
    $md.Add("| ---: | --- | ---: | ---: |")
    foreach ($summary in $sectionSummaries) {
        $summaryTitle = ConvertTo-MarkdownTableCell -Value $summary.title
        $md.Add("| $($summary.section) | $summaryTitle | $($summary.files) | $($summary.words) |")
    }
    $md.Add("")
    $md.Add("## Files By Section")

    foreach ($summary in $sectionSummaries) {
        $md.Add("")
        $summaryTitle = ConvertTo-MarkdownTableCell -Value $summary.title
        $md.Add("### $($summary.section) - $summaryTitle")
        $md.Add("")
        $md.Add("| Section | Title | Words | Source |")
        $md.Add("| --- | --- | ---: | --- |")
        foreach ($record in ($records | Where-Object { $_.top_section -eq $summary.section } | Sort-Object sort_key, file)) {
            $fileName = Split-Path -Leaf $record.file
            $link = ConvertTo-RelativeMarkdownLink -FileName $fileName
            $sectionLabel = if ([string]::IsNullOrWhiteSpace($record.section)) { "-" } else { $record.section }
            $recordTitle = ConvertTo-MarkdownTableCell -Value $record.title
            $linkLabel = ConvertTo-MarkdownLinkLabel -Value $fileName
            $md.Add("| $sectionLabel | $recordTitle | $($record.words) | [$linkLabel]($link) |")
        }
    }

    $jsonObject = [ordered]@{
        generated_by = "scripts/build-gdd-index.ps1"
        source_root = "markdown_export"
        markdown_file_count = $records.Count
        sections = $sectionSummaries
        files = $records
    }

    return [pscustomobject]@{
        Markdown = (($md -join [Environment]::NewLine) + [Environment]::NewLine)
        Json = (($jsonObject | ConvertTo-Json -Depth 6) + [Environment]::NewLine)
    }
}

$index = New-GddIndex

if ($Check) {
    if (-not (Test-Path -LiteralPath $markdownIndexPath)) {
        throw "Missing generated Markdown index: $markdownIndexPath"
    }
    if (-not (Test-Path -LiteralPath $jsonIndexPath)) {
        throw "Missing generated JSON index: $jsonIndexPath"
    }

    $currentMarkdown = Get-Content -LiteralPath $markdownIndexPath -Raw
    $currentJson = Get-Content -LiteralPath $jsonIndexPath -Raw

    if ($currentMarkdown -ne $index.Markdown) {
        throw "GDD Markdown index is stale. Run scripts\build-gdd-index.ps1."
    }
    if ($currentJson -ne $index.Json) {
        throw "GDD JSON index is stale. Run scripts\build-gdd-index.ps1."
    }

    Write-Host "GDD index check passed: $($index.Json.Length) JSON chars"
    exit 0
}

New-Item -ItemType Directory -Force -Path $indexRoot | Out-String | Write-Verbose
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($markdownIndexPath, $index.Markdown, $utf8NoBom)
[System.IO.File]::WriteAllText($jsonIndexPath, $index.Json, $utf8NoBom)
Write-Host "wrote $markdownIndexPath"
Write-Host "wrote $jsonIndexPath"
